[package]
cargo-toml-patch-comments = [
    "remove reference to readme file that is not included in published crates",
]

[[package.extra-sources]]
number = 1
file = "https://github.com/elichai/random-rs/raw/bd98b95/LICENSE-APACHE"
comments = ["https://github.com/elichai/random-rs/issues/2"]

[[package.extra-sources]]
number = 2
file = "https://github.com/elichai/random-rs/raw/bd98b95/LICENSE-MIT"

[scripts]
prep.post = [
    "cp -pav %{SOURCE1} %{SOURCE2} .",
]

