# Thanks to https://github.com/aidandenlinger/autocopr

name: Update .spec files
on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 */12 * * *'

permissions:
  contents: write

jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Set git user to github-actions[bot]
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
      - name: Check and update .spec files
        run: bash update.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
